alias python=/usr/local/bin/python3
alias ls='eza'
alias ll='ls -lah'
alias ld='ll | grep ^d'
# alias rmf='rm -rf' # only enable this if you're SURE it's smart to do so.
alias bupdate='brew update && brew upgrade'
alias blist='brew list'
alias paux='ps aux'
alias vim='nvim' # to keep me from not using it
alias grep='rg'
alias dh='df -ch' # free space in current folder
alias df='df -h' # disk free in GB by default
alias du='du -h' # disk usage in GB by default
alias duc='du -c' # disk usage for a folder
alias ..='cd ..'
alias ..2='cd ../..'
alias ..3='cd ../../..'
alias ..4='cd ../../../..'
alias cm2nl='tr "," "\n".'
alias cl2nl='tr ":" "\n"'
alias lpath='echo $PATH | cl2nl'
alias alldef='defaults domains | cm2nl'
alias reload!='RELOAD=1 source ~/.zshrc'
# alias tetris='tetriscurses'
alias 256sum='shasum -a 256'
alias pkl='~/Applications/pkl'
alias gogit='cd ~/GitRepos'
alias cd='z'
alias cdi='zi'
alias tree='eza --tree'
alias tll='ll --tree'
alias cat='bat'
