[general]
import = [
	"~/workspace/github.com/alacritty/alacritty-theme/themes/catppuccin_mocha.toml"
]
working_directory = "workspace"
[window]
opacity = 0.9
blur = true
option_as_alt = "Both"
[font]
size = 14
[terminal.shell]
program = "../.cargo/bin/nu"
args = ["-l"]
