import = ["~/.config/alacritty/themes/themes/aura.toml"]

[shell]
program = "~/.cargo/bin/nu"

[window]
decorations = "Full"
opacity = 0.75

[font]
normal = { family = "MesloLGM Nerd Font Mono", style = "Regular" }
size = 12
